word="Gracious"
print("lenght of string ",len(word))
print("first letter of string is ",word[0])
print("second letter of string is",word[1])
print("third letter of string is",word[2])
print("fourth letter of string is",word[3])
print("fifth letter of string is",word[4])
print("sixth letter of string is",word[5])
print("seventh letter of string is",word[6])
print("last letter of string is ",word[7])
print("string slice ",word[0:1])
print("string slice ",word[0:2])
print("string slice ",word[0:3])
print("string slice ",word[0:4])
print("string slice ",word[0:5])
print("string slice ",word[0:6])
print("string slice ",word[0:7])
print("string slice ",word[0:8])